"""Add document library support

Revision ID: 6273187820f4
Revises: 2c2080b25544
Create Date: 2026-03-23 10:21:51.484509

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6273187820f4'
down_revision: str | None = '2c2080b25544'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('is_library', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('documents', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'is_library')
    op.drop_column('documents', 'file_hash')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
